#!/usr/bin/env python3
"""
Extract tile pixel data from KLAD_1987_Baranov.SAV -> src/gfx_data.h.

КЛАД 1987 is a 2-COLOUR game. Each 16-byte tile is 16x8 pixels at 1bpp:
row r = bytes[2r] (left 8px) ++ bytes[2r+1] (right 8px), MSB = leftmost pixel.
Confirmed from DISP_SCANLINE_WRITE (040060): it writes 2 bytes per row to the
video ports as one 16-bit pixel word. (The old 8x8 2bpp decode was wrong — it
invented 4 colours that never appear in the emulator, which shows only blue+white.)

Usage:  python3 tools/gen_gfx_c.py > src/gfx_data.h
"""

import sys
from pathlib import Path

SAV = Path(__file__).parent.parent / "assets/uknc/KLAD_1987_Baranov.SAV"

TILE_NAMES = {
    0: "bg_empty",  1: "ladder",    2: "exit",      3: "empty3",
    4: "gold_a",    5: "gold_b",    6: "gold_c",    7: "water",
    8: "ladder2",   9: "wall_a",   10: "empty10",  11: "wall_b",
   12: "wall_c",   13: "wall_d",   14: "water2",   15: "empty15",
   16: "char0",    17: "char1",    18: "char2",    19: "char3",
   20: "char4",    21: "char5",    22: "char6",    23: "char7",
   24: "char8",    25: "char9",    26: "char10",   27: "char11",
   28: "char12",   29: "char13",   30: "char14",   31: "char15",
}

def load_prog():
    return SAV.read_bytes()[512:]   # strip 512-byte RT-11 header; prog at 001000

def decode_tile_16x8(d):
    """Decode a 16-byte tile to 16x8 1bpp. Two rules, BOTH proven from the УКНЦ
    emulator's pixels (see docs/reverse/TILE_FIDELITY.md) and consistent with the
    blit ASM (DISP_SCANLINE_WRITE @ 040060 writes 2 bytes/row at addresses P, P+1).

    The two source bytes of a row can be read two ways; which one the УКНЦ shows
    depends on how the artist authored the tile:

      DEFAULT — structural tiles (ladder, wall, water, exit): the two bytes sit at
      adjacent column groups → row r = byte[2r] (left 8px) ++ byte[2r+1] (right 8px),
      a 16-px-wide scanline. The LADDER proves this: 3C ++ 3C = ..####....####.. —
      two rails with a centre gap and full-width rungs, EXACTLY the emulator ladder.

      GOLD/treasure (tiles 4/5/6 = the 3 animation frames of the chest; pixel plane
      bytes 0-7 are all zero): the chest is authored as two OFFSET halves meant to be
      COMBINED, not placed side by side — plane0 row = FC (######..), plane1 = 3F
      (..######). OR'd → FF (########, a SOLID lid); studs A8|2A = AA. The emulator
      shows a solid-lidded chest (no centre gap), so we OR the two bytes into an 8-px
      row and double it to 16 px. Reading these side-by-side (the old bug) split the
      chest into two blocks.
    """
    pixel_plane_empty = all(b == 0 for b in d[0:8])
    colour_plane_data = any(b != 0 for b in d[8:16])
    if pixel_plane_empty and colour_plane_data:          # GOLD: OR the offset halves
        rows = []
        for r in range(8):
            b = d[2*r] | d[2*r + 1]                       # combine planes → solid 8px
            row = []
            for col in range(8):
                bit = (b >> (7 - col)) & 1
                row.append(bit); row.append(bit)          # 2:1 УКНЦ pixels → 16 wide
            rows.append(row)
        return rows
    rows = []                                             # DEFAULT: side-by-side 16px
    for r in range(8):
        row = []
        for byte in (d[2*r], d[2*r + 1]):
            for col in range(8):
                row.append((byte >> (7 - col)) & 1)
        rows.append(row)
    return rows

def tile_c_array(rows, name, index):
    out = [f"  /* {index}: {name} */", "  {"]
    for row in rows:
        out.append("    {" + ",".join(str(v) for v in row) + "},")
    out.append("  },")
    return "\n".join(out)

def main():
    prog = load_prog()
    bank = 0o17450 - 0o1000
    out = [
        "// Auto-generated by tools/gen_gfx_c.py — do not edit.",
        "// КЛАД 1987 tiles: 16x8 pixels, 1bpp (2-colour). 0 = background, 1 = foreground.",
        "// Source: tile bank 017450 (16 bytes/tile). See docs/reverse/TILE_FIDELITY.md.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "// TILE_GFX[tile_index][row(0-7)][col(0-15)] — 1bpp. 0-15 level, 16-31 character.",
        "static const uint8_t TILE_GFX[32][8][16] = {",
    ]
    for t in range(32):
        d = prog[bank + t*16 : bank + t*16 + 16]
        out.append(tile_c_array(decode_tile_16x8(d), TILE_NAMES.get(t, f"t{t}"), t))
    out.append("};")
    out.append("")
    print("\n".join(out))

if __name__ == "__main__":
    main()
