#!/usr/bin/env python3
"""
Extract tile pixel data from KLAD_1987_Baranov.SAV -> src/gfx_data.h.

КЛАД 1987 is a 2-COLOUR game. Each 16-byte tile is 16x8 pixels at 1bpp:
row r = bytes[2r] (left 8px) ++ bytes[2r+1] (right 8px), MSB = leftmost pixel.
Confirmed from DISP_SCANLINE_WRITE (040060): it writes 2 bytes per row to the
video ports as one 16-bit pixel word. (The old 8x8 2bpp decode was wrong — it
invented 4 colours that never appear in the emulator, which shows only blue+white.)

Usage:  python3 tools/gen_gfx_c.py > src/gfx_data.h
"""

import sys
from pathlib import Path

SAV = Path(__file__).parent.parent / "assets/uknc/KLAD_1987_Baranov.SAV"

TILE_NAMES = {
    0: "bg_empty",  1: "ladder",    2: "exit",      3: "empty3",
    4: "gold_a",    5: "gold_b",    6: "gold_c",    7: "water",
    8: "ladder2",   9: "wall_a",   10: "empty10",  11: "wall_b",
   12: "wall_c",   13: "wall_d",   14: "water2",   15: "empty15",
   16: "char0",    17: "char1",    18: "char2",    19: "char3",
   20: "char4",    21: "char5",    22: "char6",    23: "char7",
   24: "char8",    25: "char9",    26: "char10",   27: "char11",
   28: "char12",   29: "char13",   30: "char14",   31: "char15",
}

def load_prog():
    return SAV.read_bytes()[512:]   # strip 512-byte RT-11 header; prog at 001000

def decode_tile_16x8(d):
    """Decode a 16-byte tile to 16x8 1bpp.

    Default (ladder/wall/water — data in the pixel plane / both planes): the УКНЦ
    blit lays out row r = byte[2r] (left 8px) ++ byte[2r+1] (right 8px). This keeps
    ladders as 2 rails and the water surface — DO NOT change.

    Special case — GOLD/treasure tiles: their PIXEL plane (bytes 0-7) is all zero;
    the graphic lives only in the COLOUR plane (bytes 8-15) as a single 8x8 chest.
    Read 16x8 it gets split into two blocks (wrong). So for these tiles we decode
    the colour plane as an 8x8 chest and double it horizontally to fill 16px → ONE
    chest (matches the emulator / video clips). Only affects pixel-plane-empty tiles.
    """
    pixel_plane_empty = all(b == 0 for b in d[0:8])
    colour_plane_data = any(b != 0 for b in d[8:16])
    if pixel_plane_empty and colour_plane_data:
        rows = []
        for r in range(8):
            cb = d[8 + r]                      # one colour byte per row = 8px
            row = []
            for col in range(8):
                bit = (cb >> (7 - col)) & 1
                row.append(bit); row.append(bit)   # double each px → 16 wide, one chest
            rows.append(row)
        return rows
    # default: 16x8, two 8px bytes side by side
    rows = []
    for r in range(8):
        row = []
        for byte in (d[2*r], d[2*r + 1]):
            for col in range(8):
                row.append((byte >> (7 - col)) & 1)
        rows.append(row)   # 16 wide
    return rows

def tile_c_array(rows, name, index):
    out = [f"  /* {index}: {name} */", "  {"]
    for row in rows:
        out.append("    {" + ",".join(str(v) for v in row) + "},")
    out.append("  },")
    return "\n".join(out)

def main():
    prog = load_prog()
    bank = 0o17450 - 0o1000
    out = [
        "// Auto-generated by tools/gen_gfx_c.py — do not edit.",
        "// КЛАД 1987 tiles: 16x8 pixels, 1bpp (2-colour). 0 = background, 1 = foreground.",
        "// Source: tile bank 017450 (16 bytes/tile). See docs/reverse/TILE_FIDELITY.md.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "// TILE_GFX[tile_index][row(0-7)][col(0-15)] — 1bpp. 0-15 level, 16-31 character.",
        "static const uint8_t TILE_GFX[32][8][16] = {",
    ]
    for t in range(32):
        d = prog[bank + t*16 : bank + t*16 + 16]
        out.append(tile_c_array(decode_tile_16x8(d), TILE_NAMES.get(t, f"t{t}"), t))
    out.append("};")
    out.append("")
    print("\n".join(out))

if __name__ == "__main__":
    main()
