#!/usr/bin/env python3
"""Generate src/levels_data.h from УКНЦ level JSON files.
Usage: python3 tools/gen_levels_c.py > src/levels_data.h
"""
import json, os, sys

def main():
    base = os.path.join(os.path.dirname(__file__), '..',
                        'assets', 'uknc', 'levels')
    levels = []
    for i in range(1, 11):
        path = os.path.join(base, f'level_{i:02d}.json')
        with open(path) as f:
            levels.append(json.load(f))

    out = []
    out.append('// Auto-generated by tools/gen_levels_c.py — do not edit.')
    out.append('// Source: assets/uknc/levels/level_NN.json')
    out.append('#pragma once')
    out.append('#include <stdint.h>')
    out.append('')
    out.append('// LEVEL_TILES[level][row][col] — original tile indices 0-15')
    out.append('static const uint8_t LEVEL_TILES[10][22][32] = {')
    for lv in levels:
        out.append('  {')
        for row in lv['tiles']:
            cells = ', '.join(f'{t:2d}' for t in row)
            out.append(f'    {{ {cells} }},')
        out.append('  },')
    out.append('};')
    out.append('')
    out.append('// LEVEL_SPAWNS[level][entity][col_row]')
    out.append('// entity 0=player, 1=enemy1, 2=enemy2; -1 if absent')
    out.append('static const int8_t LEVEL_SPAWNS[10][3][2] = {')
    for lv in levels:
        sp = lv.get('spawn', {})
        def pos(key):
            e = sp.get(key)
            return (e['col'], e['row']) if e else (-1, -1)
        pl = pos('player')
        e1 = pos('enemy1')
        e2 = pos('enemy2')
        out.append(f'  {{ {{{pl[0]},{pl[1]}}}, {{{e1[0]},{e1[1]}}}, {{{e2[0]},{e2[1]}}} }},')
    out.append('};')

    print('\n'.join(out))

if __name__ == '__main__':
    main()
